# Generated by Django 4.2.20 on 2025-03-28 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
